services:
  _defaults:
    autowire: true
    autoconfigure: true
  Pixel\DirectoryBundle\Controller\Website\:
    resource: '../../Controller/Website'

  Pixel\DirectoryBundle\Repository\:
    resource: '../../Repository'